# Generated by Django 3.1 on 2020-08-31 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delegate_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Scheduled Date')),
                ('venue', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('core_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.delegate')),
            ],
        ),
    ]
