# Generated by Django 3.1 on 2020-09-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200901_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
