# Generated by Django 3.1 on 2020-10-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delegate_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_picture/default-profile-picture1.jpg', null=True, upload_to='profile_picture/'),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('numberOfRegistrations', models.IntegerField()),
                ('committee_description', models.CharField(max_length=1000)),
                ('linkToBackgroundGuide', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.event')),
            ],
        ),
    ]
